### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by ghost** [ucodery/fyeah#3]
1. Please create a release of this package, otherwise, to install it directly via Pip it one can use:

`pip install git+https://github.com/ucodery/fyeah.git@367f0a2a44c3feec1052a1e24c922e86e2aa7081`

2. Please update `python_requires` information so that it can be installed in the latest version of Python (>3.9):

```
Collecting git+https://github.com/ucodery/fyeah.git@367f0a2a44c3feec1052a1e24c922e86e2aa7081
  Cloning https://github.com/ucodery/fyeah.git (to revision 367f0a2a44c3feec1052a1e24c922e86e2aa7081) to c:\users\xxxxxx\appdata\local\temp\pip-req-build-p4hj1zjv
  Running command git clone -q https://github.com/ucodery/fyeah.git 'C:\Users\xxxxxx\AppData\Local\Temp\pip-req-build-p4hj1zjv'
  Running command git rev-parse -q --verify 'sha^367f0a2a44c3feec1052a1e24c922e86e2aa7081'
  Running command git fetch -q https://github.com/ucodery/fyeah.git 367f0a2a44c3feec1052a1e24c922e86e2aa7081
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
ERROR: Package 'f-yeah' requires a different Python: 3.9.5 not in '<3.9,>=3.6'
WARNING: You are using pip version 21.1.3; however, version 21.2.4 is available.
You should consider upgrading via the 'c:\python39\python.exe -m pip install --upgrade pip' command.
```

**Comment by ucodery** [comment]
Hi and thanks for the suggestions.

1. This module has been available on pypi.org since this repo existed: https://pypi.org/project/f-yeah/
2. Yes, I would like to make this modification to support more modern pythons. However it does not currently because the C extension currently fails to compile for >= 3.9. I am planning to fix this
